# On tag creation this GitHub Action will form a Changelog and release.
name: release
on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 #v4.2.0
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}
          
      - name: Fetch all tags
        run: git fetch --force --tags
      - uses: WillAbides/setup-go-faster@8af5eb44e6d2676b48dfd4730ee3902f41d59584 #v1.7.0
        with:
          go-version: "1.23.x"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200 # v6.0.0
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
