on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 #v4.2.0
      - uses: ministryofjustice/github-actions/code-formatter@63d84d475bc20877f741d768dd9c2d89af51170d #18.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}