on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 #v4.2.1
      - uses: ministryofjustice/github-actions/code-formatter@eaec2bb18f6dd19dd0fcb3cc48f7803a3731b7e5 #18.1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}