on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      - uses: ministryofjustice/github-actions/code-formatter@d904b22c56096882839357ed0273739a8d775787 #18.1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}