name: test
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "Makefile"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "Makefile"

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # Checkout your project with git
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 #v4.2.0

      # Install Go on the VM running the action.
      - uses: WillAbides/setup-go-faster@a0ff5217a7d2567ed6ff1aa2b7d8f9d58173b2c9 #v1.14.0
        with:
          go-version: "1.23.x"

      # Install gotestfmt on the VM running the action.
      - name: Set up gotestfmt
        uses: haveyoudebuggedit/gotestfmt-action@7dd37bbcc925453b6d7465164cf3bcbd87bc691d #v2
        with:
          # Optional: pass GITHUB_TOKEN to avoid rate limiting.
          token: ${{ secrets.GITHUB_TOKEN }}

      # Run tests with nice formatting. Save the original log in /tmp/gotest.log
      - name: Run tests
        run: |
          set -euo pipefail
          go test -json -race -covermode=atomic -coverprofile=coverage.out -v ./... 2>&1 | tee /tmp/gotest.log | gotestfmt

      # Upload the original go test log as an artifact for later review.
      - name: Upload test log
        uses: actions/upload-artifact@84480863f228bb9747b473957fcc9e309aa96097 #v4.4.2
        if: always()
        with:
          name: test-log
          path: /tmp/gotest.log
          if-no-files-found: error

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 #v4.5.0
