name: staticcheck
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # Checkout your project with git
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      # Install Go on the VM running the action.
      - uses: WillAbides/setup-go-faster@a0ff5217a7d2567ed6ff1aa2b7d8f9d58173b2c9 #v1.14.0
        with:
          go-version: "1.23.x"

      - name: Perform staticcheck on codebase
        uses: dominikh/staticcheck-action@fe1dd0c3658873b46f8c9bb3291096a617310ca6 #v1.3.1
        with:
          version: "latest"
          install-go: false

      - name: Install gofumpt
        run: |
          go install mvdan.cc/gofumpt@latest

      - name: Run gofumpt command
        run: |
          gofumpt -l -w ./

      - name: golangci-lint
        uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 #v6
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest
